### ISSUE TITLE
Separate game engine into its own repo

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/ai-battle-webworkers#1]
The game engine needs to be in its own repo because its used by the ai-battle-webworkers repo, the ai-battle-testing-website repo, and the hero-starter repo. It's likely it will also be used by the ai-battle-website repo in the future.

**Comment by natedsaint** [comment]
thought it would close when merged but I guess that's only when it goes to master?

**Comment by Asuza** [comment]
Surely other repos have issues that are closed for development branches? I don't really know how it works.

**Comment by natedsaint** [comment]
derp: it had to be in a commit message, not the PR data. I'll just close this: for future reference put one of these keywords in there https://help.github.com/articles/closing-issues-via-commit-messages/
